### ISSUE TITLE
(X-Wing) Unhandled exception and unable to open map

### ISSUE THREAD

**Issue by scotsdez** [MikeG621/YOGEME#86]
While creating a mission, after adding a B-Wing while the map screen was open, I got the below error - on saving and reopening the mission in Yogeme, I'm now unable to open the map for this mission due to the error.

Unhandled exception (Index was outside the bounds of the array):
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Idmr.Yogeme.MapForm.Import(FlightGroupCollection fg)
   at Idmr.Yogeme.MapForm..ctor(Settings settings, FlightGroupCollection fg, EventHandler dataModifiedCallback)
   at Idmr.Yogeme.XwingForm.menuMap_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolBar.OnButtonClick(ToolBarButtonClickEventArgs e)
   at System.Windows.Forms.ToolBar.WmReflectCommand(Message& m)
   at System.Windows.Forms.ToolBar.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9167.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
YOGEME
    Assembly Version: 1.14.1.21479
    Win32 Version: 1.14.1.21479
    CodeBase: file:///D:/Games/Yogeme/YOGEME.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9176.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9166.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Idmr.Platform
    Assembly Version: 5.8.0.26505
    Win32 Version: 5.8.0.0
    CodeBase: file:///D:/Games/Yogeme/bin/Idmr.Platform.DLL
----------------------------------------
Idmr.Common
    Assembly Version: 1.3.1.29352
    Win32 Version: 1.3.1.29352
    CodeBase: file:///D:/Games/Yogeme/bin/Idmr.Common.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by scotsdez** [comment]
Mission file uploaded to: https://drive.google.com/file/d/1lULsCYZagCKKtzLfMZA77UlA7p-UnNLD/view?usp=sharing for reference.

**Comment by MikeG621** [comment]
Alright, I'll take a look.

Was it instantly upon adding the FG, when changing it to B-wing, or
something else?
--

**Comment by MikeG621** [comment]
If you switch it back to Y-wing (or anything else, really) then the map can be opened again.  It has to do with the special way B-wings are handled.  I know where it finally fails, just trying to chase it backwards now.

**Comment by MikeG621** [comment]
Change the craft to anything else, then back to B-Wing. That'll sort the issue out and you'll be able to open the Map with the B-wing again.
